#!/usr/bin/env python3
from __future__ import annotations

import json
import pprint
from pathlib import Path
from typing import Any, Dict

ROOT_DIR = Path(__file__).resolve().parents[1]
RULE_DIR = ROOT_DIR / "rules" / "ja"
TS_OUT = ROOT_DIR / "src" / "generated" / "rules_bundle.ts"
PY_OUT = ROOT_DIR / "python_impl" / "generated_rules.py"


def load_rules() -> Dict[str, Any]:
    with (RULE_DIR / "core.json").open("r", encoding="utf-8") as f:
        core = json.load(f)
    with (RULE_DIR / "patterns.json").open("r", encoding="utf-8") as f:
        patterns = json.load(f)
    with (RULE_DIR / "counters.json").open("r", encoding="utf-8") as f:
        counters = json.load(f)
    return {
        "core": core,
        "patterns": patterns,
        "counters": counters,
    }


def write_typescript(bundle: Dict[str, Any]) -> None:
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(bundle, ensure_ascii=False, indent=2)
    content = "\n".join(
        [
            "// @generated by scripts/generate_rules_artifacts.py",
            "import type { RuleBundle } from \"../rules/types.js\";",
            "",
            f"export const GENERATED_RULE_BUNDLE = {payload} as RuleBundle;",
            "",
        ]
    )
    TS_OUT.write_text(content, encoding="utf-8")


def write_python(bundle: Dict[str, Any]) -> None:
    payload = pprint.pformat(bundle, width=120, sort_dicts=False)
    content = "\n".join(
        [
            "# @generated by scripts/generate_rules_artifacts.py",
            "from __future__ import annotations",
            "",
            "from typing import Any, Dict",
            "",
            f"GENERATED_RULES: Dict[str, Any] = {payload}",
            "",
        ]
    )
    PY_OUT.write_text(content, encoding="utf-8")


def main() -> None:
    bundle = load_rules()
    write_typescript(bundle)
    write_python(bundle)
    print(f"Generated: {TS_OUT}")
    print(f"Generated: {PY_OUT}")


if __name__ == "__main__":
    main()
