use serde_json::{Map, Value};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir.parent().expect("repo root");
    let rule_dir = repo_root.join("rules/ja");

    println!(
        "cargo:rerun-if-changed={}",
        rule_dir.join("core.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        rule_dir.join("patterns.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        rule_dir.join("counters.json").display()
    );

    let core = read_json(&rule_dir.join("core.json"));
    let patterns = read_json(&rule_dir.join("patterns.json"));
    let counters = read_json(&rule_dir.join("counters.json"));

    let mut out = String::new();
    out.push_str("// @generated by build.rs\n");
    out.push_str("static CORE_RULES: CoreRules = ");
    out.push_str(&gen_core(&core));
    out.push_str(";\n\n");

    out.push_str("static PATTERN_DEFS: &[PatternDef] = &[");
    out.push_str(&gen_patterns(&patterns));
    out.push_str("];\n\n");

    out.push_str("static COUNTER_DEFS: &[CounterDef] = &[");
    out.push_str(&gen_counters(&counters));
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("generated_rules.rs"), out).expect("write generated_rules.rs");
}

fn read_json(path: &Path) -> Value {
    let raw = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {}", path.display(), e))
}

fn q(s: &str) -> String {
    serde_json::to_string(s).expect("quote string")
}

fn token_slice(value: &Value) -> String {
    let arr = value.as_array().expect("token array");
    let parts: Vec<String> = arr
        .iter()
        .map(|v| q(v.as_str().expect("token string")))
        .collect();
    format!("&[{}]", parts.join(", "))
}

fn str_slice_opt(value: Option<&Value>) -> String {
    match value.and_then(Value::as_array) {
        Some(arr) => {
            let parts: Vec<String> = arr
                .iter()
                .map(|v| q(v.as_str().expect("surface string")))
                .collect();
            format!("&[{}]", parts.join(", "))
        }
        None => "&[]".to_string(),
    }
}

fn gen_core(core: &Value) -> String {
    let variants = core
        .get("variants")
        .and_then(Value::as_object)
        .expect("core.variants");
    let default_variant = core
        .get("defaultVariant")
        .and_then(Value::as_object)
        .expect("core.defaultVariant");

    let digits = core
        .get("digits")
        .and_then(Value::as_object)
        .expect("core.digits");

    let mut digit_entries: Vec<String> = Vec::new();
    for n in 0..=9 {
        let key = n.to_string();
        let tokens = digits
            .get(&key)
            .unwrap_or_else(|| panic!("core.digits.{}", key));
        digit_entries.push(token_slice(tokens));
    }

    let special_hundreds = map_num_tokens(
        core.get("specialHundreds")
            .and_then(Value::as_object)
            .expect("core.specialHundreds"),
    );
    let special_thousands = map_num_tokens(
        core.get("specialThousands")
            .and_then(Value::as_object)
            .expect("core.specialThousands"),
    );

    let small_units = core
        .get("smallUnits")
        .and_then(Value::as_object)
        .expect("core.smallUnits");

    let big_units = core
        .get("bigUnits")
        .and_then(Value::as_array)
        .expect("core.bigUnits");
    let big_entries: Vec<String> = big_units
        .iter()
        .map(|entry| {
            let obj = entry.as_object().expect("bigUnit obj");
            let pow10 = obj
                .get("pow10")
                .and_then(Value::as_u64)
                .expect("bigUnit.pow10");
            let reading = token_slice(obj.get("reading").expect("bigUnit.reading"));
            format!("({}, {})", pow10, reading)
        })
        .collect();

    let minus = token_slice(core.get("minus").expect("core.minus"));

    format!(
        "CoreRules {{ \
            variants: Variants {{ \
                zero: ZeroVariants {{ rei: {}, zero: {} }}, \
                four: FourVariants {{ yon: {}, shi: {} }}, \
                seven: SevenVariants {{ nana: {}, shichi: {} }}, \
                nine: NineVariants {{ kyu: {}, ku: {} }} \
            }}, \
            default_variant: DefaultVariant {{ \
                zero: {}, four: {}, seven: {}, nine: {} \
            }}, \
            digits: [{}], \
            special_hundreds: &[{}], \
            special_thousands: &[{}], \
            small_units_10: {}, \
            small_units_100: {}, \
            small_units_1000: {}, \
            big_units: &[{}], \
            minus: {} \
        }}",
        q(variants
            .get("zero")
            .and_then(|v| v.get("rei"))
            .and_then(Value::as_str)
            .expect("variants.zero.rei"),),
        q(variants
            .get("zero")
            .and_then(|v| v.get("zero"))
            .and_then(Value::as_str)
            .expect("variants.zero.zero"),),
        q(variants
            .get("four")
            .and_then(|v| v.get("yon"))
            .and_then(Value::as_str)
            .expect("variants.four.yon"),),
        q(variants
            .get("four")
            .and_then(|v| v.get("shi"))
            .and_then(Value::as_str)
            .expect("variants.four.shi"),),
        q(variants
            .get("seven")
            .and_then(|v| v.get("nana"))
            .and_then(Value::as_str)
            .expect("variants.seven.nana"),),
        q(variants
            .get("seven")
            .and_then(|v| v.get("shichi"))
            .and_then(Value::as_str)
            .expect("variants.seven.shichi"),),
        q(variants
            .get("nine")
            .and_then(|v| v.get("kyu"))
            .and_then(Value::as_str)
            .expect("variants.nine.kyu"),),
        q(variants
            .get("nine")
            .and_then(|v| v.get("ku"))
            .and_then(Value::as_str)
            .expect("variants.nine.ku"),),
        gen_zero_variant(
            default_variant
                .get("zero")
                .and_then(Value::as_str)
                .expect("default.zero")
        ),
        gen_four_variant(
            default_variant
                .get("four")
                .and_then(Value::as_str)
                .expect("default.four")
        ),
        gen_seven_variant(
            default_variant
                .get("seven")
                .and_then(Value::as_str)
                .expect("default.seven"),
        ),
        gen_nine_variant(
            default_variant
                .get("nine")
                .and_then(Value::as_str)
                .expect("default.nine")
        ),
        digit_entries.join(", "),
        special_hundreds.join(", "),
        special_thousands.join(", "),
        token_slice(small_units.get("10").expect("smallUnits.10")),
        token_slice(small_units.get("100").expect("smallUnits.100")),
        token_slice(small_units.get("1000").expect("smallUnits.1000")),
        big_entries.join(", "),
        minus,
    )
}

fn map_num_tokens(obj: &Map<String, Value>) -> Vec<String> {
    let mut pairs: Vec<(u8, String)> = obj
        .iter()
        .map(|(k, v)| {
            (
                k.parse::<u8>()
                    .unwrap_or_else(|_| panic!("invalid numeric key: {}", k)),
                token_slice(v),
            )
        })
        .collect();
    pairs.sort_by_key(|(k, _)| *k);
    pairs
        .into_iter()
        .map(|(k, tokens)| format!("({}, {})", k, tokens))
        .collect()
}

fn gen_zero_variant(v: &str) -> &'static str {
    match v {
        "rei" => "ZeroVariant::Rei",
        "zero" => "ZeroVariant::Zero",
        _ => panic!("unknown zero variant: {}", v),
    }
}

fn gen_four_variant(v: &str) -> &'static str {
    match v {
        "yon" => "FourVariant::Yon",
        "shi" => "FourVariant::Shi",
        _ => panic!("unknown four variant: {}", v),
    }
}

fn gen_seven_variant(v: &str) -> &'static str {
    match v {
        "nana" => "SevenVariant::Nana",
        "shichi" => "SevenVariant::Shichi",
        _ => panic!("unknown seven variant: {}", v),
    }
}

fn gen_nine_variant(v: &str) -> &'static str {
    match v {
        "kyu" => "NineVariant::Kyu",
        "ku" => "NineVariant::Ku",
        _ => panic!("unknown nine variant: {}", v),
    }
}

fn gen_patterns(patterns: &Value) -> String {
    let obj = patterns
        .get("patterns")
        .and_then(Value::as_object)
        .expect("patterns.patterns");

    let mut items: Vec<String> = Vec::new();
    for (id, pat) in obj {
        let pat_obj = pat.as_object().expect("pattern object");
        let rules = pat_obj
            .get("rules")
            .and_then(Value::as_array)
            .expect("pattern.rules");

        let rule_items: Vec<String> = rules
            .iter()
            .map(|rule| {
                let rule_obj = rule.as_object().expect("pattern rule obj");
                let when_tail_in = str_slice_opt(rule_obj.get("whenTailIn"));

                let rewrite_tail = match rule_obj.get("rewriteTail").and_then(Value::as_object) {
                    Some(rw) => {
                        let mut keys: Vec<&String> = rw.keys().collect();
                        keys.sort();
                        let entries: Vec<String> = keys
                            .into_iter()
                            .map(|k| {
                                let to = rw.get(k).and_then(Value::as_str).expect("rewrite val");
                                format!("RewriteDef {{ from: {}, to: {} }}", q(k), q(to))
                            })
                            .collect();
                        format!("&[{}]", entries.join(", "))
                    }
                    None => "&[]".to_string(),
                };

                let use_form = match rule_obj.get("useForm").and_then(Value::as_str) {
                    Some(v) => format!("Some({})", q(v)),
                    None => "None".to_string(),
                };

                format!(
                    "TailRuleDef {{ when_tail_in: {}, rewrite_tail: {}, use_form: {} }}",
                    when_tail_in, rewrite_tail, use_form
                )
            })
            .collect();

        let default_form = q(pat_obj
            .get("defaultForm")
            .and_then(Value::as_str)
            .expect("pattern.defaultForm"));

        items.push(format!(
            "PatternDef {{ id: {}, rules: &[{}], default_form: {} }}",
            q(id),
            rule_items.join(", "),
            default_form
        ));
    }

    items.join(", ")
}

fn gen_counters(counters: &Value) -> String {
    let obj = counters
        .get("counters")
        .and_then(Value::as_object)
        .expect("counters.counters");

    let mut items: Vec<String> = Vec::new();
    for (id, counter) in obj {
        let cobj = counter.as_object().expect("counter object");
        let surface = cobj.get("surface").and_then(Value::as_object);

        let prefix = str_slice_opt(surface.and_then(|s| s.get("prefix")));
        let suffix = str_slice_opt(surface.and_then(|s| s.get("suffix")));

        let compose = match cobj.get("compose") {
            Some(v) => format!("Some({})", gen_compose(v)),
            None => "None".to_string(),
        };

        let default_mode = match cobj.get("defaultMode").and_then(Value::as_str) {
            Some(v) => format!("Some({})", q(v)),
            None => "None".to_string(),
        };

        let modes = match cobj.get("modes").and_then(Value::as_object) {
            Some(modes_obj) => {
                let mut mode_keys: Vec<&String> = modes_obj.keys().collect();
                mode_keys.sort();
                let mode_items: Vec<String> = mode_keys
                    .into_iter()
                    .map(|mode_id| {
                        let mode_compose = modes_obj
                            .get(mode_id)
                            .and_then(Value::as_object)
                            .and_then(|m| m.get("compose"))
                            .expect("mode.compose");
                        format!(
                            "ModeDef {{ id: {}, compose: {} }}",
                            q(mode_id),
                            gen_compose(mode_compose)
                        )
                    })
                    .collect();
                format!("&[{}]", mode_items.join(", "))
            }
            None => "&[]".to_string(),
        };

        items.push(format!(
            "CounterDef {{ id: {}, prefix: {}, suffix: {}, compose: {}, default_mode: {}, modes: {} }}",
            q(id),
            prefix,
            suffix,
            compose,
            default_mode,
            modes
        ));
    }

    items.join(", ")
}

fn gen_compose(compose: &Value) -> String {
    let cobj = compose.as_object().expect("compose obj");
    match cobj
        .get("type")
        .and_then(Value::as_str)
        .expect("compose.type")
    {
        "concat" => format!(
            "Compose::Concat({})",
            token_slice(cobj.get("suffixReading").expect("suffixReading"))
        ),
        "pattern" => {
            let pattern_id = q(cobj
                .get("patternId")
                .and_then(Value::as_str)
                .expect("patternId"));
            let forms_obj = cobj.get("forms").and_then(Value::as_object).expect("forms");
            let mut form_keys: Vec<&String> = forms_obj.keys().collect();
            form_keys.sort();
            let form_items: Vec<String> = form_keys
                .into_iter()
                .map(|k| {
                    let tokens = token_slice(forms_obj.get(k).expect("form tokens"));
                    format!("FormDef {{ key: {}, tokens: {} }}", q(k), tokens)
                })
                .collect();

            format!(
                "Compose::Pattern(PatternCompose {{ pattern_id: {}, forms: &[{}] }})",
                pattern_id,
                form_items.join(", ")
            )
        }
        "exceptions_first" => {
            let exceptions_obj = cobj
                .get("exceptions")
                .and_then(Value::as_object)
                .expect("exceptions object");
            let mut ex_keys: Vec<&String> = exceptions_obj.keys().collect();
            ex_keys.sort();
            let exception_items: Vec<String> = ex_keys
                .into_iter()
                .map(|key| {
                    let tokens = token_slice(exceptions_obj.get(key).expect("exception tokens"));
                    let key_num = key
                        .parse::<i64>()
                        .map(|n| format!("Some({})", n))
                        .unwrap_or_else(|_| "None".to_string());
                    format!(
                        "ExceptionDef {{ key: {}, key_num: {}, tokens: {} }}",
                        q(key),
                        key_num,
                        tokens
                    )
                })
                .collect();

            let fallback = gen_fallback(
                cobj.get("fallback")
                    .expect("exceptions_first.fallback missing"),
            );

            format!(
                "Compose::ExceptionsFirst(ExceptionsFirstCompose {{ exceptions: &[{}], fallback: {} }})",
                exception_items.join(", "),
                fallback
            )
        }
        other => panic!("unknown compose.type: {}", other),
    }
}

fn gen_fallback(fallback: &Value) -> String {
    let fobj = fallback.as_object().expect("fallback object");
    match fobj
        .get("type")
        .and_then(Value::as_str)
        .expect("fallback.type")
    {
        "concat" => format!(
            "FallbackCompose::Concat({})",
            token_slice(
                fobj.get("suffixReading")
                    .expect("fallback.concat.suffixReading")
            )
        ),
        "pattern" => {
            let pattern_id = q(fobj
                .get("patternId")
                .and_then(Value::as_str)
                .expect("patternId"));
            let forms_obj = fobj.get("forms").and_then(Value::as_object).expect("forms");
            let mut form_keys: Vec<&String> = forms_obj.keys().collect();
            form_keys.sort();
            let form_items: Vec<String> = form_keys
                .into_iter()
                .map(|k| {
                    let tokens = token_slice(forms_obj.get(k).expect("form tokens"));
                    format!("FormDef {{ key: {}, tokens: {} }}", q(k), tokens)
                })
                .collect();

            format!(
                "FallbackCompose::Pattern(PatternCompose {{ pattern_id: {}, forms: &[{}] }})",
                pattern_id,
                form_items.join(", ")
            )
        }
        other => panic!("unknown fallback.type: {}", other),
    }
}
